# Generated by Django 5.2.4 on 2025-08-02 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviewDetailed", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("picture", models.ImageField(upload_to="products/")),
            ],
        ),
    ]
