# Generated by Django 5.2.4 on 2025-08-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviewDetailed", "0002_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="avgRating",
            field=models.IntegerField(default=3),
        ),
    ]
