# Generated by Django 5.2.4 on 2025-08-02 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviewDetailed", "0003_product_avgrating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="picture",
            field=models.ImageField(upload_to="media/"),
        ),
    ]
