# Generated by Django 5.2.4 on 2025-08-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviewDetailed", "0004_alter_product_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="avgRating",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="product",
            name="picture",
            field=models.ImageField(upload_to=""),
        ),
    ]
