# Generated by Django 5.2.4 on 2025-08-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviewDetailed", "0005_alter_product_avgrating_alter_product_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="aiOverview",
            field=models.TextField(blank=True, null=True),
        ),
    ]
